language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

sudo: false

before_install:
    - composer selfupdate

install: composer update --no-interaction

notifications:
    email: kostasxx@yahoo.com