language: php

php:
    - 5.5
    - 5.6

sudo: false

before_install:
    - composer selfupdate

install: composer update --no-interaction

notifications:
    email: kostas.christofilos@rocketgraph.com